---
# TargetGroupBinding for ArgoCD
# Connects ArgoCD service to ALB target group for HTTPS access
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd-tgb
  namespace: argocd
spec:
  serviceRef:
    name: argocd-server
    port: 80
  targetGroupARN: "" # Injected by Terraform
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "sg-0347be3ffdc3fe6a0"
        ports:
          - protocol: TCP
            port: 8080
