---
# TargetGroupBinding for ArgoCD
# Connects ArgoCD service to ALB target group for HTTPS access
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd-tgb
  namespace: argocd
spec:
  serviceRef:
    name: argocd-server
    port: 8080
  targetGroupARN: "arn:aws:elasticloadbalancing:eu-north-1:610964304971:targetgroup/devops-quiz-eks-argocd-tg/43e51904f6c132ac"
  targetType: ip
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: "sg-0347be3ffdc3fe6a0"
        ports:
          - protocol: TCP
            port: 8080
