---
# =============================================================================
# External Secrets Operator
# =============================================================================
# Syncs secrets from AWS SSM Parameter Store to Kubernetes Secrets
# Used for OpenAI API key and other sensitive configuration
# IRSA role ARN must be updated with actual value from Terraform outputs
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before application workloads
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.20
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: external-secrets
        # TODO: Update with actual IRSA role ARN from Terraform output: external_secrets_role_arn
        - name: serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn
          value: REPLACE_WITH_TERRAFORM_OUTPUT_external_secrets_role_arn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
