{{- if .Values.externalSecrets.enabled -}}
---
# SecretStore: Defines how to access AWS SSM Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "quiz-app.serviceAccountName" . }}

---
# ExternalSecret: Syncs OpenAI API key from SSM to Kubernetes Secret
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .target }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .property }}
      remoteRef:
        key: {{ .key }}
{{- end }}
{{- end }}
