{{- if and .Values.jenkins.enabled .Values.externalSecrets.enabled }}
# SecretStore for Jenkins namespace
# Connects to AWS SSM Parameter Store using IRSA
# The External Secrets Operator service account already has the required IAM role
# Created by terraform: external_secrets_role_arn
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Values.externalSecrets.namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
{{- end }}
